name: Restify Server

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x.x  # Use the Node.js version you need
# You may need to adjust this command based on your project's setup
    - name: Install dependencies
      run: |
         cd bot
         pwd
         npm install    

    - name: Start Restify server
      run: npm run dev:teamsfx  # Replace with the command to start your Restify server
